#!/bin/bash

EC2_HOME=/home/ec2-user


# ----------------------- Install Common Yum Packages ------------------------

sudo yum update -y
sudo yum install -y git docker


# ------------------------ Install Docker and Compose ------------------------

usermod -a -G docker ec2-user
newgrp docker
sudo systemctl start docker
sudo systemctl enable docker

DOCKER_COMPOSE_VERSION=v2.27.0
DOCKER_COMPOSE_ASSET=docker-compose-linux-x86_64
DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download
DOCKER_CONFIG=$EC2_HOME/.docker
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL $DOCKER_COMPOSE_URL/$DOCKER_COMPOSE_VERSION/$DOCKER_COMPOSE_ASSET \
  -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

sudo chown -R ec2-user:ec2-user $DOCKER_CONFIG
