version: "3.8"

volumes:
  postgres-data:

services:
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/pfm:cached
    networks:
      - pfm_network
    command: sleep infinity
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ..:/pfm:cached
    networks:
      - pfm_network
    command: sleep infinity
    env_file:
      - postgres.env

  db:
    image: postgres:16.3-alpine
    restart: unless-stopped
    env_file:
      - postgres.env
    networks:
      - pfm_network

networks:
  pfm_network:
